- name: Install nginx
  apt:
    name: nginx
    state: present
  tags: nginx

- name: Enable nginx
  systemd:
    name: nginx
    enabled: yes
  tags: nginx

- name: Remote default nginx configuration
  file:
    name: '{{ item }}'
    state: absent
  loop:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default
  tags: nginx

- name: Copy wp config file
  template:
    src: otus-devops-server.loc.conf.j2
    dest: /etc/nginx/sites-enabled/otus-devops-server.loc.conf
    mode: 644
    owner: root
    group: root
  notify: Restart nginx
  tags: nginx